# Generated by Django 4.0.1 on 2022-02-14 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_item_title', models.CharField(max_length=50)),
                ('content_item_author', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_list_title', models.CharField(max_length=50)),
                ('content_list_rating', models.CharField(choices=[('SAFE_FOR_WORK', 'safeForWork'), ('NOT_SAFE_FOR_WORK', 'notSafeForWork')], default='SAFE_FOR_WORK', max_length=50)),
                ('content_list_author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='content_lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_link_host_name', models.CharField(max_length=50)),
                ('content_link_url', models.URLField()),
                ('content_item', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='content_item_links', to='seas.contentitem')),
            ],
        ),
        migrations.AddField(
            model_name='contentitem',
            name='content_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='content_list_items', to='seas.contentlist'),
        ),
    ]
