# Generated by Django 4.0.1 on 2022-01-28 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentItemTitle', models.CharField(max_length=50)),
                ('contentItemAuthor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ContentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentListTitle', models.CharField(max_length=50)),
                ('contentListRating', models.CharField(choices=[('SUITABLE_FOR_WORK', 'suitableForWork'), ('NOT_SUITABLE_FOR_WORK', 'notSuitableForWork')], default='SUITABLE_FOR_WORK', max_length=50)),
                ('contentItems', models.ManyToManyField(related_name='contentItems', to='seas.ContentItem')),
                ('contentListAuthor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contentLists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contentitem',
            name='contentLinks',
            field=models.ManyToManyField(related_name='contentLinks', to='seas.ContentLink'),
        ),
    ]
