# Generated by Django 4.0.1 on 2022-01-28 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentitem',
            name='contentLinks',
        ),
        migrations.RemoveField(
            model_name='contentlist',
            name='contentItems',
        ),
        migrations.AddField(
            model_name='contentitem',
            name='contentList',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contentItems', to='seas.contentlist'),
        ),
        migrations.AddField(
            model_name='contentlink',
            name='contentHostName',
            field=models.CharField(default='todo', max_length=50),
        ),
        migrations.AddField(
            model_name='contentlink',
            name='contentItem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contentLinks', to='seas.contentitem'),
        ),
        migrations.AddField(
            model_name='contentlink',
            name='contentUrl',
            field=models.URLField(default='todo'),
        ),
    ]
