# Generated by Django 4.0.1 on 2022-02-17 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentlist',
            name='content_list_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='content_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
