# Generated by Django 4.0.1 on 2022-01-28 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seas', '0002_remove_contentitem_contentlinks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentlink',
            old_name='contentHostName',
            new_name='contentLinkHostName',
        ),
        migrations.RenameField(
            model_name='contentlink',
            old_name='contentUrl',
            new_name='contentLinkUrl',
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='contentList',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contentListItems', to='seas.contentlist'),
        ),
        migrations.AlterField(
            model_name='contentlink',
            name='contentItem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contentItemLinks', to='seas.contentitem'),
        ),
    ]
