# Generated by Django 4.0.1 on 2022-01-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seas', '0003_rename_contenthostname_contentlink_contentlinkhostname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentlist',
            name='contentListRating',
            field=models.CharField(choices=[('SAFE_FOR_WORK', 'safeForWork'), ('NOT_SAFE_FOR_WORK', 'notSafeForWork')], default='SAFE_FOR_WORK', max_length=50),
        ),
    ]
