# Generated by Django 4.0.1 on 2022-02-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seas', '0003_alter_contentlist_content_list_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentlist',
            name='content_list_title',
            field=models.CharField(max_length=50),
        ),
    ]
